# Generated by Django 6.0.7 on 2026-07-31 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('morning', '🌅 Morning'), ('study', '📚 Study'), ('workout', '🏃 Workout'), ('expense', '💰 Expense'), ('sleep', '😴 Sleep'), ('water', '💧 Water'), ('achievement', '🏆 Achievement'), ('reminder', '⏰ Reminder')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_reminder', models.BooleanField(default=True)),
                ('morning_time', models.TimeField(default='06:00')),
                ('study_reminder', models.BooleanField(default=True)),
                ('study_time', models.TimeField(default='10:00')),
                ('workout_reminder', models.BooleanField(default=True)),
                ('workout_time', models.TimeField(default='17:00')),
                ('expense_reminder', models.BooleanField(default=True)),
                ('expense_time', models.TimeField(default='20:00')),
                ('sleep_reminder', models.BooleanField(default=True)),
                ('sleep_time', models.TimeField(default='22:00')),
                ('water_reminder', models.BooleanField(default=True)),
                ('water_interval', models.IntegerField(default=60, help_text='Minutes between reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
