# Generated by Django 6.0.7 on 2026-07-31 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='📌', max_length=10)),
                ('color', models.CharField(default='#FF6B6B', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todo_categories',
                'ordering': ['order'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='📝', max_length=10)),
                ('priority', models.CharField(choices=[('high', '🔴 High'), ('medium', '🟡 Medium'), ('low', '🟢 Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.todocategory')),
            ],
            options={
                'db_table': 'todos',
                'ordering': ['date', 'order'],
            },
        ),
    ]
