# Generated by Django 6.0.7 on 2026-07-31 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_clean', models.IntegerField()),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recovery_milestones',
                'ordering': ['-days_clean'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('porn_count', models.IntegerField(default=0)),
                ('masturbation_count', models.IntegerField(default=0)),
                ('urge_level', models.IntegerField(default=0, help_text='1-10')),
                ('mood', models.CharField(default='😊', max_length=20)),
                ('energy_level', models.IntegerField(default=5, help_text='1-10')),
                ('stress_level', models.IntegerField(default=5, help_text='1-10')),
                ('sleep_hours', models.FloatField(default=0)),
                ('trigger', models.CharField(blank=True, choices=[('phone', '📱 Phone'), ('loneliness', '😔 Loneliness'), ('stress', '😰 Stress'), ('instagram', '📸 Instagram'), ('youtube', '▶️ YouTube'), ('boredom', '😴 Boredom'), ('other', 'Other')], max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('clean_day', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recovery_logs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
