# Generated by Django 6.0.7 on 2026-07-31 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='💻', max_length=10)),
                ('status', models.CharField(choices=[('planning', '📋 Planning'), ('in_progress', '🚀 In Progress'), ('review', '🔍 Review'), ('completed', '✅ Completed'), ('on_hold', '⏸ On Hold')], default='planning', max_length=20)),
                ('priority', models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🔴 High'), ('critical', '🔥 Critical')], default='medium', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True)),
                ('deployment_link', models.URLField(blank=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-priority', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='projects.project')),
            ],
            options={
                'db_table': 'project_checklist',
                'ordering': ['order'],
            },
        ),
    ]
