# Generated by Django 6.0.7 on 2026-07-31 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_study_hours', models.FloatField(default=0)),
                ('study_days', models.IntegerField(default=0)),
                ('habit_completion_rate', models.FloatField(default=0)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clean_days', models.IntegerField(default=0)),
                ('relapse_days', models.IntegerField(default=0)),
                ('avg_sleep_hours', models.FloatField(default=0)),
                ('avg_water_glasses', models.FloatField(default=0)),
                ('total_workout_minutes', models.IntegerField(default=0)),
                ('avg_daily_score', models.FloatField(default=0)),
                ('xp_gained', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-start_date'],
                'unique_together': {('user', 'period', 'start_date')},
            },
        ),
    ]
