# Generated by Django 6.0.7 on 2026-07-31 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('water_glasses', models.IntegerField(default=0, help_text='Number of glasses')),
                ('sleep_hours', models.FloatField(default=0)),
                ('calories_consumed', models.IntegerField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
                ('running_km', models.FloatField(default=0)),
                ('pushups', models.IntegerField(default=0)),
                ('workout_minutes', models.IntegerField(default=0)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('mood', models.CharField(default='😊', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitness_logs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
